# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: master_workflow

on: push

jobs:
  build:
    runs-on: ${{ matrix.runsOn }}
    env:
      DEVELOPER_DIR: "/Applications/${{ matrix.xcode }}/Contents/Developer"

    steps:
    - name: checkout
      uses: actions/checkout@v3

    - name: Build On ${{ matrix.name }}
      continue-on-error: false
      run: |
        xcodebuild -scheme  NavigationLargeTitleSwiftUI -destination '${{ matrix.destination }}' build
    
    strategy:
      fail-fast: false
      matrix:
        include:
          - destination: 'platform=iOS Simulator,name=iPhone 14'
            runsOn: macos-12
            xcode: "Xcode_14.2.app"
            name: "iPhone 14, iOS Latest, Xcode 14.2"
